#!/bin/bash
#
## Written by K. Garner - run fmriprep with neurodesk
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=6

fmriprep /data/VALCERT \
         /data/VALCERT/derivatives/fmriprep \
         participant \
         --fs-license-file \
         /home/jovyan/neurodesktop-storage/imaging_cert_value_7T_pipeline/dependencies/freesurfer/freesurfer.txt \
         --output-spaces T1w MNI152NLin2009cAsym fsaverage fsnative \
         --participant-label 140 \
         --nprocs 6 --mem 10000 \
         --skip_bids_validation \
         -w /data/work/ \
         -v
