#!/bin/bash
#
# written by K. Garner - the purpose of this code is to run mriqc with neurodesk

export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=6 # specify the number of threads you want to use

mriqc /data/VALCERT \
      /data/VALCERT/derivatives/mriqc \
      group \
      --work-dir /data/work \
      --nprocs 6 --mem_gb 10000 \
      -v