function run_contrast_comps(sub, fpath)
%% written by K. Garner
% run contrast computations
% for the subject identified by the number sub,
% run the edited spm_contrasts_ed to reprint
% out the contrast images (as not saved by nipype)
% spm_contrasts_ed is taken from the spm toolbox, I have commented
% out the lines that check whether a contrast image has previously
% been written so that all images are written by default
%
% NOTE: to run this on inode, make sure you have already previously
% done the following in terminal:
% ml matlab
% ml spm/12
%
% -- INPUTS:
%  ----sub: subject number [string]
%  ----fpath: filepath to data - e.g. '/scratch/qbi/uqkgarn1/data/derivatives/spm/'
% -- OUTPUTS:
%  ----con, ess, F & T images generated by SPM
%
% Assumes BIDS data structure. references to filepaths need amending
% for general use

%% clear any possible conflicting info
clear SPM

%% add spm to path
addpath(genpath('/opt/ohpc/pub/apps/spm12/'))

%% define subject folder and move to it
hme_path = pwd;
addpath(hme_path);

%% get sub deets
full_file_path = sprintf([fpath 'sub-%s/ses-02/flglm'], sub);

cd(full_file_path);
load('SPM.mat');

SPM = spm_contrasts_ed(SPM);

%% go home
cd(hme_path)

end